[workspace]
members = [
    "asynchronous",
    "cli",
    "closures",
    "collections",
    "concurrency",
    "enums",
    "error_handling",
    "features",
    "generics",
    "io",
    "iterators",
    "logs",
    "macros",
    "ownership",
    "sandbox",
    "smart_pointers",
    "string",
    "structs",
    "tests",
    "traits",
    "tree",
    "validation",
]
